services:
  # -------------------------------
  # FastAPI backend (Telco Churn)
  # -------------------------------
 services:
  - type: web
    name: telco-churn-api
    env: docker
    plan: free

    dockerfilePath: api/Dockerfile
    dockerContext: api   # ðŸ”¥ THIS IS THE FIX

    autoDeploy: true
    healthCheckPath: /health

    envVars:
      - key: PORT
        value: 8000

    

  # -------------------------------
  # Streamlit frontend
  # -------------------------------
  - type: web
    name: telco-churn-streamlit
    env: docker
    plan: free
    dockerfilePath: streamlit/Dockerfile
    dockerContext: .
    autoDeploy: true
    envVars:
      - key: API_URL
        value: https://telco-churn-api.onrender.com
